"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/Provider";
import Menu from "./Components/Shared/Menu";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// Remove the export of metadata
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 1000 
    });
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Menu>{children}</Menu>
        </Providers>
      </body>
    </html>
  );
}
